
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        enabled: true

# Configure dashboard access
ingressRoute:
  dashboard:
    enabled: true
    # Make sure we define the proper route
    annotations: {}
    labels: {}
    matchRule: "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
    middlewares: []
    entryPoints: ["websecure"]
    tls: {}

# Ensure API is enabled properly
api:
  dashboard: true
  insecure: true  # For testing only, set to false in production

# The rest of your configuration
service:
  enabled: true
  type: LoadBalancer

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

additionalArguments:
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"