entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        enabled: true

ingressRoute:
  dashboard:
    enabled: true

service:
  enabled: true
  type: LoadBalancer

providers:
  kubernetesCRD:
    enabled: true

additionalArguments:
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"
  - "--api.dashboard=true"
